### ISSUE TITLE
Script errors, System.Runtime or dependency

### ISSUE THREAD

**Issue by Sellular** [lpww/doomgrader#16]
inflating: System.ServiceModel.Primitives.dll  
The entry point method could not be loaded due to Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

This is the error I get when running the script. I just installed Mono v6, any ideas?

mono --version:
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

**Comment by lpww** [comment]
Hey :) I'm sorry you are having trouble with the script. 

That error is coming from depotdownloader. I'm not sure what's causing it. I'm on mono 6.4.0 as that is the latest available version in the stable Manjaro repository. 

I would suggest you try to first try to run depotdownloader directly:

1. Change to the depotdownloader directory `cd ~/doomgrader/depotdownloader`
2. Download the first chunk with `./depotdownloader -app 782330 -depot 782332 -manifest 4641765937586464647 -username "YOUR_STEAM_USERNAME" -password "YOUR_STEAM_PASSWORD" -remember-password -dir "~/doomgrader/files"`

If you are still running into problems, you can try running depotdownloader with `dotnet` instead of `mono`. We are swapping out the `dotnet` dependency to `mono` for improved compatibility but it's technically not supported by depotdownloader. It could be causing issues with your system. If you have access to `dotnet` in your distro, you could try using that:

1. Install `dotnet`. More info [here](https://wiki.archlinux.org/index.php/.NET_Core) (don't forget to add it to your path if required on your distro)
2. Remove the depotdownloader directory `rm -rf ~/doomgrader/depotdownloader`
3. Comment out [this line](https://github.com/lpww/doomgrader/blob/master/doomgrader.sh#L57) by putting a `#` at the start
4. Run doomgrader again `./doomgrader`

Let me know how you get on with these 2 steps!

**Comment by Sellular** [comment]
Seems like the latter worked for me! Have to run steam in offline mode and turn off auto updates but we're all good!

**Comment by lpww** [comment]
Great! I'm glad you got it working :) 

You shouldn't have to run steam in offline mode or disable updates. It won't verify the game files until a new update is released and the next update is going to remove the anti cheat anyway! 

If the game gets updated and still doesn't work on Linux for any reason, you can just re-copy the downgraded files with `./doomgrader -c`. You won't have to re download the files as doomgrader keeps a copy of them
